POST http://localhost:8080/mpc/ HTTP/1.1
content-type: application/json

{
    "date": "2020-11-04 00:00:00",
    
    "disturbances":[
        {
         "Htg SP": 12.8,
         "Indoor Temp. Setpoint": 12.8,
         "Occupancy Flag": 0,
         "PPD": 99.9,
         "Coil Power": 0.0,
         "MA Temp.": 8.492557,
         "Sys Out Temp.": 8.863671,
         "dt": "2020-11-04 00:00:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": -3.0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 00:15:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 00:30:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 00:45:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 01:00:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 01:15:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 01:30:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 01:45:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 02:00:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 02:15:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 02:30:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-11-04 02:45:00",
         "Occupancy Flag": 0,
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        }
    ]
}

