POST http://localhost:8080/mpc/ HTTP/1.1
content-type: application/json

{
    "date": "2020-11-01 00:00:00",
    "obs":{
        "Indoor Temp.": 0,
        "Htg SP": 0,
        "Indoor Temp. Setpoint": 12.8,
        "Occupancy Flag": 0,
        "PPD": 0,
        "Coil Power": 0,
        "MA Temp.": 0,
        "Sys Out Temp.": 0
    },
    "weather":[
        {
         "dt": "2020-10-21 00:00:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 00:15:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 00:30:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 00:45:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 01:00:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 01:15:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 01:30:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 01:45:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 02:00:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 02:15:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 02:30:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        },
        {
         "dt": "2020-10-21 02:45:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Direct Solar Rad.": 0,
         "Indoor Temp.": 22
        }
    ]
}

