POST http://localhost:8080/mpc/ HTTP/1.1
content-type: application/json

{
    "year": 2020,
    "month": 10,
    "day": 20,
    "weather":[
        {
         "dt": "2020-10-21 00:00:00",
         "Outdoor Temp.": 0,
         "Outdoor RH": 95,
         "Wind Speed": 4.1,
         "Wind Direction": 290,
         "Diff. Solar Rad.": 0,
         "Direct Solar Rad.": 0,
         "Indoor Temp. Setpoint": 12.8,
         "Indoor Temp.": 22,
         "Occupancy Flag": 0
        },
        {
         "dt": "2020-10-21 00:15:00",
         "Outdoor Temp.": 1.8,
         "Outdoor RH": 95.25,
         "Wind Speed": 4.1,
         "Wind Direction": 265,
         "Diff. Solar Rad.": 0,
         "Direct Solar Rad.": 0,
         "Indoor Temp. Setpoint": 12.8,
         "Indoor Temp.": 22,
         "Occupancy Flag": 0
        }
    ]
}